---

- name: Create .ssh dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: 0700

- name: Write .ssh/config
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: 0600
    force: yes
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}" # workarround
  loop: "{{ [groups] }}"



